In [6]:
import numpy as np
import torch as th

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x, y)

array([-3,  6, -3])

In [8]:
xs = np.array([[1, 2, 3],
               [1, 2, 3],
               [1, 2, 3],
               [1, 2, 3]])
ys = np.array([[4, 5, 6],
               [4, 5, 6],
               [4, 5, 6],
               [4, 5, 6]])
np.cross(xs, ys)

array([[-3,  6, -3],
       [-3,  6, -3],
       [-3,  6, -3],
       [-3,  6, -3]])

In [9]:
def my_cross(xs, ys):
    re = np.empty_like(xs)
    re[:, 0] = xs[:, 1] * ys[:, 2] - xs[:, 2] * ys[:, 1]
    re[:, 1] = xs[:, 2] * ys[:, 0] - xs[:, 0] * ys[:, 2]
    re[:, 2] = xs[:, 0] * ys[:, 1] - xs[:, 1] * ys[:, 0]
    return re

In [10]:
my_cross(xs, ys)

array([[-3,  6, -3],
       [-3,  6, -3],
       [-3,  6, -3],
       [-3,  6, -3]])

In [12]:
xs = np.array([[1, 2, 3],
               [1, 2, 3],
               [1, 2, 3],
               [1, 2, 3]])
ys = np.array([[4, 5, 6],
               [4, 5, 6],
               [4, 5, 6],
               [4, 5, 6]])
xs = th.Tensor(xs)
ys = th.Tensor(ys)

In [14]:
th.cross(xs.T, ys.T)

tensor([[-3., -3., -3., -3.],
        [ 6.,  6.,  6.,  6.],
        [-3., -3., -3., -3.]])

In [15]:
th.cross(xs, ys)

tensor([[-3.,  6., -3.],
        [-3.,  6., -3.],
        [-3.,  6., -3.],
        [-3.,  6., -3.]])

In [17]:
a = th.Tensor([1, 2, 3])
b = th.Tensor([4, 5, 6])
th.cross(a, b)

tensor([-3.,  6., -3.])