In [1]:
import numpy as np

In [12]:
a = np.array([[1,2,3], 
              [4,5,6]])
print(np.cumsum(a, axis=-1))
print(np.cumsum(a, axis=1))

[[ 1  3  6]
 [ 4  9 15]]
[[ 1  3  6]
 [ 4  9 15]]


In [13]:
axis = 0
r = np.zeros_like(a)
for i in range(a.shape[axis]):
    if i != 0:
        r[i, :] = r[i - 1, :] + a[i, :]
    else:
        r[i, :] = a[i, :]
print(r)

[[1 2 3]
 [5 7 9]]
