In [1]:
import numpy as np
import open3d as o3d
import open3d.core as o3c

In [2]:
np_points = np.array([[10, 2, 30], [1, 20, 3]],dtype=np.float32)
print(np_points.max(0))
print(np_points.max(1))

[10. 20. 30.]
[30. 20.]


In [3]:
def cast_to_py_tensor(pybind_tensor):
    py_tensor = o3c.Tensor([])
    py_tensor.shallow_copy_from(pybind_tensor)
    return py_tensor

In [4]:
t_points = o3c.Tensor.from_numpy(np_points)
tl_points = o3c.TensorList.from_tensor(t_points, inplace=True)

tl_points_tensor = cast_to_py_tensor(tl_points.as_tensor())
print(tl_points_tensor.max(0))
print(tl_points_tensor.max(1))

[10.0 20.0 30.0]
Tensor[shape={3}, stride={1}, Float32, CPU:0, 0x56487459c040]
[30.0 20.0]
Tensor[shape={2}, stride={1}, Float32, CPU:0, 0x56487459c7b0]


In [5]:
# Verify that there's no memory copy.
print(tl_points_tensor)
np_points[0, 0] = 100
print(tl_points_tensor)

[[10.0 2.0 30.0],
 [1.0 20.0 3.0]]
Tensor[shape={2, 3}, stride={3, 1}, Float32, CPU:0, 0x5648744bc550]
[[100.0 2.0 30.0],
 [1.0 20.0 3.0]]
Tensor[shape={2, 3}, stride={3, 1}, Float32, CPU:0, 0x5648744bc550]
