In [1]:
import numpy as np
import open3d as o3d
import open3d.core as o3c

In [6]:
np_points = np.array([[10, 2, 30], [1, 20, 3]],dtype=np.int32)
print(np_points.max(0))
print(np_points.max(1))

[10 20 30]
[30 20]


In [11]:
def cast_to_py_tensor(pybind_tensor):
    py_tensor = o3c.Tensor([])
    py_tensor.shallow_copy_from(pybind_tensor)
    return py_tensor

In [12]:
t_points = o3c.Tensor.from_numpy(np_points)
tl_points = o3c.TensorList.from_tensor(t_points, inplace=True)

tl_points_tensor = cast_to_py_tensor(tl_points.as_tensor())
print(tl_points_tensor.max(0))
print(tl_points_tensor.max(1))

[100 20 30]
Tensor[shape={3}, stride={1}, Int32, CPU:0, 0x56487459c040]
[100 20]
Tensor[shape={2}, stride={1}, Int32, CPU:0, 0x5648745a0ca0]


In [13]:
# Verify that there's no memory copy.
print(tl_points_tensor)
np_points[0, 0] = 100
print(tl_points_tensor)

[[100 2 30],
 [1 20 3]]
Tensor[shape={2, 3}, stride={3, 1}, Int32, CPU:0, 0x56487459c6a0]
[[100 2 30],
 [1 20 3]]
Tensor[shape={2, 3}, stride={3, 1}, Int32, CPU:0, 0x56487459c6a0]


In [19]:
colors = o3c.Tensor(
    [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1],
     [1, 1, 1]], dtype=o3c.Dtype.Float32)

In [24]:
labels = o3c.Tensor(
    [0, 3, 3, 2, 1, 3], dtype=o3c.Dtype.Int64
)

In [25]:
colors[labels]

[[1.0 0.0 0.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [0.0 0.0 1.0],
 [0.0 1.0 0.0],
 [1.0 1.0 1.0]]
Tensor[shape={6, 3}, stride={3, 1}, Float32, CPU:0, 0x564874594d10]